name: "CI Tests"

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  XCODE_VERSION: "15.0.1"

jobs:
  run_tests:
    name: Peek Tests
    runs-on: macos-13
    timeout-minutes: 20
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run Tests
      shell: bash
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install xcbeautify
        swift test | xcbeautify
